### ISSUE TITLE
prompt's `--update-db` when run in any other directory than the `HOME` directory

### ISSUE THREAD

**Issue by prodicus** [prodicus/xkcd-dl#1]
If you try to run `xkcd-dl` from another directory it will ask you to run `xkcd-dl --update-db` again.

[https://www.reddit.com/r/linux/comments/3srvu0/made_a_cli_app_to_download_xkcd_reviews_please/cx0s1lk](https://www.reddit.com/r/linux/comments/3srvu0/made_a_cli_app_to_download_xkcd_reviews_please/cx0s1lk)

**Comment by Kickball** [comment]
This was fixed in #9.
