### ISSUE TITLE
Opening on the comic on the command line, options?

### ISSUE THREAD

**Issue by BlitzKraft** [prodicus/xkcd-dl#25]
My go to image viewer is `feh`, but my `xdg-open` default is `eog`. I looked at `img2text` but it seems unsuitable for stick figures. 

This is not really helpful: 
![2016-04-11-064215_956x1076_scrot](https://cloud.githubusercontent.com/assets/6516167/14425915/970dd2f0-ffb0-11e5-952a-bcba97cce46e.png)

The comic in the picture is #1665, city talk pages. 

Consider this issue an RFC on using feh as default and xdg-open if there is no feh.

**Comment by prodicus** [comment]
@BlitzKraft I thought over it and I think we would deviate from our main aim here, (downloading the comics).

What's your take on it?

**Comment by BlitzKraft** [comment]
This is a cool little feature. Instead of going to the browser, I like a command, say:
```
xkcd #1024
```
To show me the comic, or take me to the webpage. It is fine as is with the functionality, but this will be handy. This is also in the to-do list in read me, which is why I wanted to do it.

**Comment by prodicus** [comment]
I will leave that to you to decide upon. :+1:

**Comment by BlitzKraft** [comment]
@prodicus What program did you use to create the gifs in the readme? The new help looks slightly different (although the options are still fully valid).  

Could you update that?

**Comment by prodicus** [comment]
Was kind of manual work. refer [http://tasdikrahman.me/2015/11/07/creating-gif-from-screencast/](http://tasdikrahman.me/2015/11/07/creating-gif-from-screencast/).

This was back when I didn't know about [https://asciinema.org/](https://asciinema.org/). Feel free to make a PR for this

**Comment by BlitzKraft** [comment]
Covered by PR #26. Closing this.

**Comment by prodicus** [comment]
:+1:

**Comment by prodicus** [comment]
@BlitzKraft I uploaded `v0.1.0` on pypi. Can you test it out?

**Comment by BlitzKraft** [comment]
Just opened an issue about the module version. Installed just fine, from pip3.

**Comment by prodicus** [comment]
Hey @BlitzKraft .

As we have refactored the code considerably, I was thinking of writing tests for them. What say?

**Comment by BlitzKraft** [comment]
Yes, we should. I have been looking for an excuse to learn to write tests. I haven't written any before. 

If you already know how, I would love to start off of yours.

**Comment by prodicus** [comment]
That sounds great. If you want some real examples on how to write them, you can look over at [vocabulary](https://github.com/prodicus/vocabulary), [spammy](https://github.com/prodicus/spammy) or [pyzipcode-cli](https://github.com/prodicus/pyzipcode-cli). 

For relevant material on them, I recently suggested some to one of my friends. You can find the links [here](https://github.com/prodicus/thanos/issues/5)

Ping me if anythings sounds confusing
