### ISSUE TITLE
Version 0.1.0 - Unknown references to version, VERSION and __version__

### ISSUE THREAD

**Issue by BlitzKraft** [prodicus/xkcd-dl#28]
The installation was smooth. The above mentioned variables, from cli.py threw an error. I commented them out and everything was fine. 

I don't understand the purpose of the module 'version'. What is it for?

**Comment by prodicus** [comment]
I fixed it and released new version. `pip install -U xkcd-dl` shall do. 

Coming to the question. Well, it's just a design choice. Using it I don't have to remember to change the version in each and every place of the module

**Comment by prodicus** [comment]
fixed in 1f0002cef4cdd37396e3edb7b3e181dae6adeebb
