### ISSUE TITLE
XKCD 961 Eternal Flame animated gif

### ISSUE THREAD

**Issue by antonc42** [prodicus/xkcd-dl#37]
https://xkcd.com/961/

The image is an animated gif, but is renamed with .jpg extension when downloaded.

**Comment by prodicus** [comment]
Hey @antonc42

Looks like this is an edge case. Will take a look over the weekend. If
someone is up to it. There's not much to patch here. So feel free to make a
PR

Cheers!

**Comment by antonc42** [comment]
After looking, it does seem to be a simple fix. I submitted a PR #38. I tested it by downloading all the comics again and it found a few more gifs than just 961. There was also 1116, 1264, and 1331.

**Comment by prodicus** [comment]
Good work @antonc42 👍 

Thanks for the contribution. Will update the pip module in a while

**Comment by antonc42** [comment]
No problem! Thank you for the awesome app!

**Comment by prodicus** [comment]
I am glad you liked it @antonc42 :)

Do you use it quite frequently?

Regards,
Tasdik

[image: http://]*tasdikrahman.me*
<http://tasdikrahman.me/>

[image: https://in.linkedin.com/in/tasdikrahman]
<https://in.linkedin.com/in/tasdikrahman>   <http://github.com/prodicus>
<http://www.quora.com/Tasdik-Rahman>
<https://plus.google.com/+TasdikRahman>   <https://twitter.com/tasdikrahman>

**Comment by antonc42** [comment]
I just discovered it recently. I'm using it to create a screensaver slideshow of the comics.

**Comment by prodicus** [comment]
Ah. That's nice. Please keep me posted on this project of yours. Would love to have a look at it. 

Cheers!

**Comment by antonc42** [comment]
There's not really much to it. I use your app to download all the comics to a directory and then point my screensaver at it. The only other thing I did was to put the alt text at the bottom of the image. I just do that with a little bash script. https://gist.github.com/antonc42/01742c560eb741b4ca543c966fe22cc0

**Comment by prodicus** [comment]
Looks good man. @antonc42 

Would love to put your project on the README.md under a title like `projects using xkcd-dl` if you don't mind

**Comment by antonc42** [comment]
Sure, fine by me.
